spring:
  application:
    name: mycollegeAppStudentServices
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPool
    url: jdbc:mysql://localhost:3306/mycollegedb
    username: root
    password:    
    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql

logging:
  level:
    org:
      springframework: INFO
    com:
      wcc: 
        distancecalculationapp:
          services:
            controller: INFO

server:
  port: 8801
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka
  instance:
    preferIpAddress: true  
    instance-id: