DROP TABLE IF EXISTS `student_course`;

CREATE TABLE IF NOT EXISTS `student_course` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(350) DEFAULT NULL,
  `course` varchar(350) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `email` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ABDUL HARIS BIN HAJI LAKAR','PATENT FORMALITY & INTERNATIONAL REGISTRATION','03-2299 8421','haris@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('KAMAL BIN KORMIN','FORMALITY EXAMINATION AND DOCUMENTATION','03-2299 8422','kamal@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NUR SAIDATUN SHEILA BINTI TALIB','EAST COST ZONE (KUANTAN)','09-517 3759','sheila@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('RAZHUAN BIN HUSIN','PATENT SCIENCE & TRADITIONAL KNOWLEDGE','03-2299 8442','razhuan@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AHMAD ZAHIDI B. AZIZAN','RUANA, SECRUTIZATION & ARCHIVE','03-2299 8734','zahidi@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('KULJIT SINGH A/L OJAGAR SINGH','COPYRIGHT','03-2299 8410','kuljit@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD RAZLAN BIN HJ ABD. HAMID','SEKSYEN PEMERIKSAAN SUBSTANTIF DAN RAYUAN','03-2299 8877','razlanhamid@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('REDZUAN BIN ALI','PATENT FORMALITY & INTERNATIONAL REGISTRATION','','redzuan@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ROSLINDA BINTI MD RASHID','FORMALITY EXAMINATION AND DOCUMENTATION','03-2299 8665','roslinda@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AZAHAR BIN ABDUL RAZAB','ASSISTANT DIRECTOR GENERAL (REGISTRATION & COMPLIANCE)','03-2299 8763','azaharazab@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('RUHAIZA BINTI MOHAMAD RASHIDAN','FINANCE','03-2299 8909','aiza@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('RYZUL BIN OSMAN BASAH','UNIT CARIAN & PEMERIKSAAN','03-2299 8706','ryzul@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AZLINA BINTI ABDUL HAMID','MANAGEMENT SERVICES','03-2299 8462','azlina@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('BADIAH BINTI HJ. ABBAS','UNIT PEMERIKSAAN SUBSTANTIF','03-2299 8772','badiah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NOOR MOHAMAD HAZMAN BIN HAMID','BUSINESS DEVELOPMENT','03-2299 8481','hazman@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SITI MARIAM BINTI SOLEHAN (WFH)','CERTIFICATION & RENEWAL','03-2299 8644','sitimariam@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AHMAD ISMADI BIN OTHMAN','PROCUREMENT SECTION','03-2299 8678','ismadi@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('HADAFI BIN SELAMAT','UNIT PETROKIMIA & OLEOKIMIA','03-2299 8683','hadafi@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AKTAR BIN SAHARI','CORPORATE COMMUNICATION','03-2299 8525','akhtar@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SR. SYED SAIFUL NIZAM BIN SYED MUBARAT','TECHNICAL & FACILITIES MANAGEMENT','03-2299 8934','syedsaiful@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('HASNAH BINTI YAHYA','UNIT BIOTEKNOLOGI & MIKROORGANISMA','03-2299 8569','hasnah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('YUSNIEZA SYARMILA BINTI YUSOFF','POLICY & INTERNATIONAL AFFAIRS','03-2299 8962','yusnieza@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ZAITON BINTI HARIS (WFH)','INTERNATIONAL REGISTRATION (MADRID)','03-2299 8654','zaitonh@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ZAITON BINTI NORDIN','PATENT FORMALITY & INTERNATIONAL REGISTRATION','03-2299 8766','zaiton@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('LAW SHA GEK','SUB-UNIT PERMOHONAN DALAM NEGERI','03-2299 8563','lawshagek@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SHAROUL ABBAS','HUMAN RESOURCES','03-2299 8941','default@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('YUSNIEZA SYARMILA BINTI YUSOFF','ASSISTANT DIRECTOR GENERAL (ADMINISTRATION & FINANCE)','03-2299 8962','yusnieza@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SITI MARIAM BINTI SOLEHAN','WORK FROM HOME (TRADEMARK FORMALITY & INTERNATIONAL REGISTRATION)','03-2299 8644','sitimariam@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHAMAD FAIROS BIN NADIR @ HJ ISMAIL','UNIT BUKAN ORGANIK & ELEKTROKIMIA','03-2299 8682','fairos@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHAMED FAIRUZ BIN MOHD PILUS','TRADE MARK & GEOGRAPHICAL INDICATION','03-2299 8411','5ruz@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD FAIIZUDIN BIN MOHD SHARUJI','INTELLECTUAL PROPERTY ACADEMY (IPA)','03-2299 8415','faiizudin@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ZULKARNAIN BIN MUHAMMAD','TRADE MARK & GEOGRAPHICAL INDICATION','03-2299 8423','zulkarnain@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD KHAIRI BIN MOHD SAHRUM','CENTRAL ZONE (MALACCA)','06-232 4778','khairi@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SHARIFAH NADIAH BINTI SYED SHEIKH','INDUSTRIAL DESIGN & LAYOUT OF INTEGRATED CIRCUITS','03-2299 8415','nadiah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD NOR HAFIZ BIN ABD. MUNIR','INTEGRITY','03-2299 8971','norhafiz@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD RADHI BIN AHMAD','NORTHERN ZONE (PENANG)','04-383 1424','radhi@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD SUHEZEY BIN SHAFIE','SOUTHERN ZONE (JOHOR)','07-2222871','suhezey@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD SUKRI BIN MOHD NOR','UNIT FITOKIMIA & PENGETAHUAN TRADISIONAL','03-2299 8431','sukri@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD ZAKI BIN ZAKARIA','WORK FROM HOME (PATENT ENGINEERING)','011-6344 0928','zaki@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NIRWANI BINTI RAHMAN','PERFORMANCE & TRAINING','03-2299 8545','nirwani@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ABBAS SAAD','INTELLECTUAL PROPERTY MANAGEMENT','03-2299 8964','default@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NOORHISHAM BIN OTHMAN','APPLICATION','03-2299 8812','noorhisham@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('FARIDAH BINTI KASMADI','TRADEMARK FORMALITY & INTERNATIONAL REGISTRATION','03-2299 8431','faridah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NOR INTAN BINTI PAMIN','SARAWAK COURSE','082-458 073','intan@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('EN. AZAHAR BIN ABDUL RAZAB','TRADE MARK & GEOGRAPHICAL INDICATION','03-2299 8763','azaharazab@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD HISAM BIN ABU HASHIM','TRADE MARK & GEOGRAPHICAL INDICATION','03-2299 8431','hisampt@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AHMAD HAZLI BIN MOHD HISHAM','REGISTRATION','03-2299 8847','hazli@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NAZIRAH BINTI ABDUL JALIL','UNIT FORMALITI PENDENGARAN','03-2299 8643','nazirah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NUR MAZIAN BINTI MAT TAHIR','POLICY & INTERNATIONAL AFFAIRS','03-2299 8966','mazian@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NURUL HIDAYAH BINTI ARIFFIN','CENTRAL ZONE (MALACCA)','03-2299 8400','hidayah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NURZALINA BINTI BADRUDDIN','MANAGEMENT SERVICES','03-2299 8400','nurzalina@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NURZATUNNAFIZA BINTI WASIR','INFORMATION MANAGEMENT','03-2299 8530','nazza@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('PHELOMENA AK JEMBUN@JIMBUN','SARAWAK COURSE','082-459076','phelo@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('RANY SHARMILA BINTI IBRAHIM','INTEGRITY','03-2299 8975','sharmila@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ASHAARI B. AB. RAHMAN','CUSTOMER SERVICE COUNTER','03-2299 8490','ashaari@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ASMAWATI BINTI OMAR','INTELLECTUAL PROPERTY ACADEMY (IPA)','03-2299 8586','asma@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SAJARATUL ARIFFIN BIN RAHMAT','PROCUREMENT SECTION','03-2299 8820','sajaratul@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AZLIN BINTI MOHD FAHMI','PATENT ENGINEERING','03-2299 8460','azlin@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AZRI BIN ROSLAN','BUSINESS DEVELOPMENT','03-2299 8560','azriroslan@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SH. ARIFIN BIN SH. MOHD. NOOR','ASSISTANT DIRECTOR GENERAL (PLANNING & BUSINESS DEVELOPMENT)','03-2299 8443','ariffin@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('CHE NOR ESWAREZAL BIN CHE ANUAR','SERVICES','03-2299 8870','eswarezal@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SHAMSUL AZILA BINTI ANAIDIN@BAHARIN','WORK FROM HOME (PATENT SCIENCE & TRADITIONAL KNOWLEDGE)','019-2525456','shamsul@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NORANISAH BINTI ABAS','TRADEMARK FORMALITY & INTERNATIONAL REGISTRATION','03-2299 8770','anisah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NUR NAZIHAH FAIZAH BINTI FAIZUL','FINANCE','03-2299 8984','nazihah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SITI KHATIJAH AMINAH BINTI MUDA','UNIT BIOTEKNOLOGI & MIKROORGANISMA','03-2299 8689','aminah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SITI RAHMAH BINTI IDRIS','SUB-UNIT PERMOHONAN DALAM NEGERI','03-2299 8729','sitirahmah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD AMIRULHAIZAD BIN AB WAHAB','WORK FROM HOME (PATENT ENGINEERING)','03-60398632','amirulhaizad@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('TEH NORLEZA BINTI ZAKARIA','INDUSTRIAL DESIGN & LAYOUT OF INTEGRATED CIRCUITS','03-2299 8860','teh@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('VINCENT LEJAU','PATENT FORMALITY & INTERNATIONAL REGISTRATION','03-2299 8431','vincent@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('HISHAMUDIN BIN ABDUL WALAD','UNIT FORMALITI PENDENGARAN','03-2299 8621','hishamudin@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('WAN NOORAZLAN BIN WAN ARIFIN','INTERNATIONAL REGISTRATION (MADRID)','03-2299 8771','noorazlan@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('KATIJAH BINTI WAHID (WFH)','AGENT & IPOJ','010-8456415','katijah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('IDA RUSYEELA BINTI ABDUL SAMAD','INTERNAL AUDIT & QUALITY MANAGEMENT','03-2299 8913','rusyeela@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NUR SOLEHA BINTI MD YUSHOF','INTELLECTUAL PROPERTY MANAGEMENT','03-2299 8954','soleha@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ZAITON BINTI HARIS','WORK FROM HOME (TRADEMARK FORMALITY & INTERNATIONAL REGISTRATION)','03-2299 8654','zaitonh@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ZARINA BINTI JAAFAR (WFH)','CERTIFICATION & RENEWAL','03 - 77730369','zarina@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHAMAD ZULKARNIAN BIN SUPIAN','NORTHERN ZONE (PENANG)','04-3830295','zulkarnian@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NURUL SHAFIKAH BINTI ABD RAHMAN','DIRECTOR GENERAL COURSE','03-2299 8421','shafikah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('INTAN ADILA BINTI BADRUL HISHAM','CORPORATE COMMUNICATION','03-2299 8973','intanadila@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NUR AIN SYAHIRAH BINTI NORAZHAR','DEPUTY DIRECTOR GENERAL (STRATEGIC & TECHNICAL) COURSE','03-2299 8422','ainsyahirah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('HAZIMAH BINTI HASSAN','UNIT RAYUAN','03-2299 8773','hazimah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NUR AZURA BINTI ZAMAN HURI','UNIT FITOKIMIA & PENGETAHUAN TRADISIONAL','013 313 0819','azura@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NUR IZZATI BINTI MARZUKI','PERFORMANCE & TRAINING','03-2299 8928','nurizzati@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD SHAHRIN BIN SHAHARUDIN','UNIT PETROKIMIA & OLEOKIMIA','03-2299 8695','shahrin@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ASMAH BINTI KHALID','SABAH COURSE','088-254524','asmah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NAZIRA ADILA BINTI TAHZIR','REGISTRATION','03-2299 8851','nazira@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NOOR ALIFF BIN MUSA','COPYRIGHT','03-2299 8549','aliff@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NOOR JULIANA BINTI MOHAMAD @ KHALID','UNIT KIMIA ORGANIK & BAHAN','03-2299 8400','juliana@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NOR AMIZA BINTI AHMAD','TRADE MARK & GEOGRAPHICAL INDICATION','03-2299 8646','amiza@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NOR HASHILA BINTI MOHAMAD HASSIM','APPLICATION','03-2299 8810','hashila@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD JESRI BIN OMAR','SOUTHERN ZONE (JOHOR)','07-2222873','jesri@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AMALINA BINTI MAMAT','UNIT PETROKIMIA & OLEOKIMIA','03-2299 8571','amalina@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NURULATHIRAH BINTI DAGANG','INTELLECTUAL PROPERTY MANAGEMENT','03-2299 8958','nurulathirah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ANIS NURHANAN BIN AHMAD','PATENT ENGINEERING','03-2299 8447','anis@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SALMI BINTI AHMAD','CERTIFICATION & RENEWAL','03-2299 8634','salmi@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('CHE NORIAH BINTI CHE SOFF','MANAGEMENT SERVICES','03-22998739','noriah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('KHADIJAH BINTI MD. ZIN','PERFORMANCE & TRAINING','03-2299 8855','khadijah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('FADZILAH BINTI MOHD ALI @ ALI RAZUAN','INDUSTRIAL DESIGN & LAYOUT OF INTEGRATED CIRCUITS','03-2299 8861','fadzilah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MUHAMMAD BIN HASHIM','INTERNAL AUDIT & QUALITY MANAGEMENT','03-2299 8983','muhammad@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SITI NATRAH BINTI MOHAMED YUSOFF','WORK FROM HOME (PATENT SCIENCE & TRADITIONAL KNOWLEDGE)','03-8920 0623','natrah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('FARIDAH BINTI YAAKOB','TRADEMARK FORMALITY & INTERNATIONAL REGISTRATION','03-2299 8657','faridahy@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SITI RUZAIEMA BINTI ABD RAZAK','SUB-UNIT PERMOHONAN DALAM NEGERI','03-2299 8720','ruzaiema@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('GOH AI MEI','FINANCE','03-2299 8977','aimei@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SUHAILY BINTI MAHMAD','RUANA, SECRUTIZATION & ARCHIVE','03-2299 8779','suhaily@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('HANUN AFIQAH BINTI MOHD PAUZI','INTELLECTUAL PROPERTY ACADEMY (IPA)','03-2299 8963','afiqah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('HASWANI BINTI MOHD NOR','UNIT FITOKIMIA & PENGETAHUAN TRADISIONAL','','haswani@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD SOFIYUDDIN BIN MD HANIF','TECHNICAL & FACILITIES MANAGEMENT','03-2299 8544','sofiyuddin@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ZAINAB BINTI ISMAIL','CORPORATE COMMUNICATION','03-2299 8958','zainab@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('IYLIA BINTI HASHIM','LEGAL','03-2299 8980','iylia@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('YUSLIZA BINTI YUSUF','REGISTRATION','03-2299 8833','yusliza@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('JULIZIANAH JAMIL SULONG','UNIT FORMALITI PENDENGARAN','03-2299 8917','julizianah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ABDUL GAFUR BIN ABDU RAHMAT JULIANTO','FORMALITY EXAMINATION AND DOCUMENTATION','03-2299 8660','gafur@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD NAJIB BIN HISAMUDDIN','SOUTHERN ZONE (JOHOR)','07-2222873','mnajib@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ZURIAH BINTI MASROM','UNIT RAYUAN','03-2299 8755','mzuriah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NURUL NADIA BINTI KHAIRANI','PROCUREMENT SECTION','03-2299 8431','nurulnadia@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MAWAR HARTINI BINTI MD MAZLAN','COPYRIGHT','03-2299 8551','mhartini@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('KHAIRUL ZAMAN BIN MUSTAFA KAMAL','POLICY & INTERNATIONAL AFFAIRS','03-2299 8953','khairul@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SITI NOR ZUBAIDAH BINTI MOHD ZABIL','DEPUTY DIRECTOR GENERAL (MANAGEMENT) COURSE','03-2299 8423','aida@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AHMAD QHALLAFFIR IRSHAD BIN AZMAN','INTERNATIONAL REGISTRATION (MADRID)','03-2299 8718','aqhallaffir@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('KATIJAH BINTI WAHID ','WORK FROM HOME (TRADEMARK FORMALITY & INTERNATIONAL REGISTRATION)','010-8456415','katijah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('IVY ANAK ROMEO','UNIT CARIAN & PEMERIKSAAN','03-2299 8711','ivy@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD HAFIDZEE BIN HAZAMI','NORTHERN ZONE (PENANG)','04-3830715','hafidzee@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ROHADI BIN MAT RANI','PATENT FORMALITY & INTERNATIONAL REGISTRATION','03-2299 8431','rohadi@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD KHAIROL BIN GHANI','UNIT KIMIA ORGANIK & BAHAN','03-2299 8700','khairol@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NOOR HEZZELYNN MERICAN BT. MOHAMED ROSLAN MERICAN','CUSTOMER SERVICE COUNTER','03-2299 8492','hezzelynn@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NOOR SHAZWANI BT. IBRAHIM','CENTRAL ZONE (MALACCA)','06-232 4733','shazwani@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NOR RUZANNA BINTI RAZALI','UNIT PENDENGARAN EX-PARTE','03-2299 8764','ruzanna@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NOR AZLILA BINTI AHAMAD','INFORMATION MANAGEMENT','03-2299 8531','azlila@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NORAHZLIDA BINTI BUSRAH','APPLICATION','03-2299 8809','norahzlida@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NUR SALFIZA BINTI SHAARI','INFORMATION MANAGEMENT','03-2299 8515','fiza@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHAMAD AZRUL BIN MUSTAFA','MANAGEMENT SERVICES','03-2299 8733','azrul@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ZULKIFLI BIN MOHD ALI','FINANCE','03-2299 8901','zulkifli@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NORHAFIZAH BINTI MAHROR','LEGAL','03-2299 8735','norhafizah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('HANI AFIQAH BINTI MOHAMAD JAMAL','LEGAL','03-2299 8974','hani.afiqah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD SYAUFIQ BIN ABDUL LATIF','COPYRIGHT','03-2299 8921','syaufiq@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('FADZLI BIN JAAFAR','INDUSTRIAL DESIGN & LAYOUT OF INTEGRATED CIRCUITS','03-2299 8859','fadzlijaafar@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('FAIZAL BIN MOHD RUSLAN','PERFORMANCE & TRAINING','03-2299 8942','rfaizal@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('FARDHIAH RAHAH BINTI KHALID','PROCUREMENT SECTION','03-2299 8490','fardhiah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SITI NORRA BINTI RAZALLI','NORTHERN ZONE (PENANG)','04-3830715','norra@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('FAZLIANA BT MUHAMAD','CERTIFICATION & RENEWAL','03-2299 8576','fazliana@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SUDIANA BINTI MOHAMAD','SARAWAK COURSE','082-459075','sudiana@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SUHAIDA BINTI ISMAIL @ MUSTAFA','UNIT KIMIA ORGANIK & BAHAN','03-2299 8565','suhaida@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SURAIYA BINTI SHAARI','RUANA, SECRUTIZATION & ARCHIVE','03-2299 8779','suraiya@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ARNI NAZIRA BINTI AMRAN','TECHNICAL & FACILITIES MANAGEMENT','03-2299 8931','arni@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SUZIEMASLINA BINTI AHMAD SHINHIME','REGISTRATION','03-2299 8805','suzie@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHD HAFEZIE SHAHRIL BIN HANAPIAH','CUSTOMER SERVICE COUNTER','03-2299 8774','hafezie@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('LAWRENCE GEORGE','SABAH COURSE','088-233571','lawrence@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MARSITI BINTI MD. SALMIN','WORK FROM HOME (PATENT SCIENCE & TRADITIONAL KNOWLEDGE)','012-2624730','marsiti@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NURSYIDA BINTI ARIFF','DIRECTOR GENERAL COURSE','03-2299 8970','nursyida@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AZRI ALHADI BIN ABDULLAH','INTELLECTUAL PROPERTY ACADEMY (IPA)','03-2299 8703','alhadi@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AINILLAHAN BINTI KHALID','WORK FROM HOME (TRADE MARK & GEOGRAPHICAL INDICATION)','03-8727 7937','ainillahan@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MAJDAH BINTI ABDUL MUTALIB','UNIT FITOKIMIA & PENGETAHUAN TRADISIONAL','012 593 0604','majdah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NUR BASYARIYAH HUMAIRA BINTI MD FARIZ','SOUTHERN ZONE (JOHOR)','03-2299 8431','nurbasyariyah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('KHAIRUL SYAFIQ BIN SYUKRI','APPLICATION','03-2299 8849','khairulsyafiq@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHAMMAD FATHIR BIN MD. NOOR','UNIT CARIAN & PEMERIKSAAN','03-2299 8712','fathir@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MUHAMMAD AZFAR BIN AB. MALEK','POLICY & INTERNATIONAL AFFAIRS','03-2299 8429','azfar@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NOR SHAFIZA BINTI MD. ISA','BUSINESS NETWORKING & EMPOWERMENT OF BUMIPUTRA','03-2299 8589','shafiza@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NORAINI MURTI BINTI IBRAHIM','UNIT FORMALITI PENDENGARAN','03-2299 8621','noraininm@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NORDIN BIN MAMAT','UNIT RAYUAN','03-2299 8749','nordin@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SYAZWANI BINTI BURHANUDDIN','WORK FROM HOME (PATENT SCIENCE & TRADITIONAL KNOWLEDGE)','012-9412373','syazwani@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NORHAZLIDA BINTI AB. HALIM','SUB-UNIT PERMOHONAN DALAM NEGERI','03-2299 8748','hazlida@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NORSAMUDDIN BIN ABU HASSAN','PATENT FORMALITY & INTERNATIONAL REGISTRATION','03-2299 8742','samuddin@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NORYANTIE BINTI MOHAMED (WFH)','INTERNATIONAL REGISTRATION (MADRID)','03-2299 8631','noryantie@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NUR HIDAYAH BINTI HAMDAN','WORK FROM HOME (PATENT SCIENCE & TRADITIONAL KNOWLEDGE)','03-8322 1925','nurhidayah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AHMAD KHALIS BIN AHMAD AZIDI','DIRECTOR GENERAL COURSE','03-2299 8431','khalis@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MERIAM NUR BINTI AHMAD HANBALI','POLICY & INTERNATIONAL AFFAIRS','03-2299 8961','meriam@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('RAHATULKHAIRANI BINTI AHMAD ABKARI','FORMALITY EXAMINATION AND DOCUMENTATION','03-6279 0270','rahatul@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SYAHZAL EZHAN BIN MANJA','MARKETING','03-2299 8943','syahzal@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('FARIZUL HAKIM BIN MUHAMAD NOR','MANAGEMENT SERVICES','03-2299 8704','farizul@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('NURUL FAHANA BINTI MOHD NOR','CERTIFICATION & RENEWAL','03-2299 8624','nurulfahana@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AZZAHARA BINTI AZIZ','UNIT PENDENGARAN EX-PARTE','03-2299 8732','azzahara@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('ROZANAH BINTI MISKAN','APPLICATION','03-2299 8813','rozanah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MUHAMMAD FAIZ BIN MOHD ROSLAN','SUB-UNIT PERMOHONAN DALAM NEGERI','03-2299 8717','mfaiz@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SITI NOORHASIKIN BT TUMPANG','PATENT FORMALITY & INTERNATIONAL REGISTRATION','03-2299 8431','noorhasikin@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('MOHAMAD RAHIMI BIN ARAFPIN','LEGAL','03-2299 8979','rahimi@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('AZRAN BIN BOHARI','WORK FROM HOME (PATENT ENGINEERING)','03-8051 2079','azran@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SHABARIAH SALUS','SARAWAK COURSE','082-459075','shabariah@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('SITI HASLIN BINTI ABDUL GHANI','INTERNAL AUDIT & QUALITY MANAGEMENT','03-2299 8914','haslin@college.com.my');
INSERT INTO student_course(`name`, `course`, `phone`, `email`) VALUES('HANIZA BINTI BASIR','RUANA, SECRUTIZATION & ARCHIVE','03-2299 8578','bhaniza@college.com.my');
