server:
  port: 8800
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka
  instance:
    preferIpAddress: true  
    instance-id:
   
spring:
  application:
    name: mycollegeAppGateway
  cloud:
    gateway:
      default-filters:
      - name: GatewayAuthenticationAuthorizationFilter
      routes:
      - id: mycollegeAppStudentServices
        uri: lb://mycollegeAppStudentServices
        predicates:
        - Path=/mycollegeapp/services/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST